### ISSUE TITLE
Internal error when saving a new 404

### ISSUE THREAD

**Issue by yaychris** [barrelstrength/craft-sprout-seo#100]
### Description

The first request for a new 404 raises an exception, `unknown method: barrelstrength\sproutseo\elements\db\RedirectQuery::anyStatus()`. The 404 is saved and subsequent requests do not raise an exception. 

Stack attached below. Following the trace points to [this line](https://github.com/barrelstrength/craft-sprout-seo/blob/v4.0.0-beta.6/src/services/Redirects.php#L264), which happens after the 404 is saved and during the limit check.

I don't know Craft very well, but digging through the code indicates that `RedirectQuery` doesn't inherit from anything that defines an `anyStatus` method.

```
2018-08-24 11:34:57 [127.0.0.1][-][338374085017d5a2f4bbddc7b23cb7c4][error][yii\base\ErrorException:1] yii\base\ErrorException: Uncaught yii\base\UnknownMethodException: Calling unknown method: barrelstrength\sproutseo\elements\db\RedirectQuery::anyStatus() in /storage/av05576/www/public_html/releases/20180823133752/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /storage/av05576/www/public_html/releases/20180823133752/vendor/craftcms/cms/src/elements/db/ElementQuery.php(446): yii\base\Component->__call('anyStatus', Array)
#1 /storage/av05576/www/public_html/releases/20180823133752/vendor/barrelstrength/sprout-seo/src/services/Redirects.php(264): craft\elements\db\ElementQuery->__call('anyStatus', Array)
#2 /storage/av05576/www/public_html/releases/20180823133752/vendor/barrelstrength/sprout-seo/src/SproutSeo.php(139): barrelstrength\sproutseo\services\Redirects->save404Redirect('https://www.pog...', Object(craft\models\Site))
#3 [internal function]: barrelstrength\sproutseo\SproutSeo->barrelstrength\sproutseo\{closure}(Object(craft\events\ExceptionEvent))
#4 /storage/av05576/www/public_html/releases/20180823133752/vendor/y in /storage/av05576/www/public_html/releases/20180823133752/vendor/yiisoft/yii2/base/Component.php:300
```

### Steps to reproduce

1. Turn on "Log 404 Redirects" in the admin
2. Visit a URL that will 404 (needs to be one that's not already saved)

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.23 
- Sprout SEO version: 4.0.0-beta.6

**Comment by andrelopez** [comment]
Hi @yaychris 

Thanks for reaching out. This was a Craft bug and is fixed in 3.0.17 -> https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#added-7

Could you please update Craft CMS and let us know if that solves the issue?
