### ISSUE TITLE
FR: Dont hide SEO fields with custom format

### ISSUE THREAD

**Issue by McCrisp** [barrelstrength/craft-sprout-seo#116]
Hi, this is just a small FR from me, but i figured there might be others that would like this option too.

I usually create a new tab on my entries for "SEO", here the client have all their related SEO fields.

When a field, for example image or description has a custom format that fetches content form a field, that field is hidden from the SEO-tab and instead the entry-field gets a label "SEO".

![screen shot 2018-10-19 at 15 02 03](https://user-images.githubusercontent.com/13944443/47219890-6fe84d00-d3b0-11e8-9996-5913223e315c.png)

Here the image and description fields are missing. I can still edit them on the content-tab, but my clients might be confused why some entries got this and others don't.

I like the SEO label on related fields, but it would be great to be able to choose to keep the field on the SEO tab too. With just the automated content from the custom format, and the option to edit this without affecting the related field.

This is for C3.

**Comment by BenParizek** [comment]
Hey @McCrisp 

I understand the issue you are describing but we currently see this more as a workflow issue than a plugin settings issue. It would also be pretty tricky for us to solve within the plugin - from both a technical and usability perspective. I'll leave this open as a FR if anybody else wants to add ideas.

Sprout SEO aims to embrace metadata as if it was content. In most cases, the two go hand and hand and good content is composed of relevant metadata. While you can manage metadata and content separately, we see this as a deviation from the ideal scenario and the whole concept of an "SEO" tab doesn't really make sense.

In your case you already seem to be half-opting in to this approach by mapping the Title and Description fields to existing content fields so your users can focus on good content that will also be used as metadata. 

Where things get confusing is the addition of the Meta Keywords field which probably doesn't feel right as asking the client to handle as actual content so it gets delegated to another tab. However, then it feels like this SEO tab only has partial information. Perhaps consider placing that under the Description field or removing that field entirely and enabling the Meta Details "Search Meta" field which allows a user to override the Title, Description, and Keywords fields. You could then let the SEO tab just be the tab where a client can manage "SEO Overrides" that deviate from the normal content-driven SEO that they will focus on primarily.

----

From the technical side of things, the Custom Format is just adding the SEO badge in the UI to existing fields. A Custom Format can target any field or combination of fields include complex fields like Matrix fields. For us to move a field, or multiple fields, you are targeting for use in a Custom Format we would have to either completely move a field to a tab (which you can do yourself in Craft's Field Layout settings) or try to decide what we should move for you, even with complex Matrix fields, and we'd also start to have to ask you for additional info like what tab you want us to move it to and what order you want things to display in. It's not really feasible for us to manage that type of complexity, nor do I think it's necessary if you take a more content-driven SEO approach.

----

Alternatively, we could consider giving you a setting to remove the SEO badges if that might help reduce confusion if you did want to pursue an SEO tab type approach to how you set up the content model. Happy to hear more thoughts on any alternative approaches that could also help alleviate confusion for clients in different setups.
