### ISSUE TITLE
Craft 3: PHP Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by luxwan13** [barrelstrength/craft-sprout-seo#122]
### Description
I know this has been fixed for Craft 2 but this is still happening for Craft 3. I am using latest version 4.0.0-beta.13

### Steps to reproduce

1. Go to any page after enable the plugin
2.

### Additional info

- Craft version: 3.0.32
- PHP version: 7.2.12
- Database driver & version:
- Plugins & versions: 4.0.0-beta.13

**Comment by andrelopez** [comment]
Hi @luxwan13 we just released Sprout SEO beta 14 with a fix for this issue, please let us know if you see any other error.
