### ISSUE TITLE
Redirects not working with Base Url as env variable.

### ISSUE THREAD

**Issue by abrunovski** [barrelstrength/craft-sprout-seo#147]
When site's Base Url is set as env var in .env file.
sprout-seo plugin not converting env var to actual urls.
All redirects are broken.

![alt text](http://img.static.generalstudios.com/scrn1.png)

![alt text](http://img.static.generalstudios.com/scrn2.png)

### Additional info

- Craft version:  3.1.17.2
- PHP version: 7.1
- Plugins & versions: 4.0.0-beta.29

**Comment by BenParizek** [comment]
Thanks for reporting @abrunovski. We'll look into this and let you know when we have an update.

**Comment by BenParizek** [comment]
@abrunovski Thanks for reporting. This is resolved in the latest release.
