### ISSUE TITLE
Error on Redirects page

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#152]
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_isrf)

**Comment by lpbouvier** [comment]
@BenParizek I get an error landing on the redirects page. I am no able to create a redirect either, I get an error on save; _"Argument 1 passed to craft\services\Structures::appendToRoot() must be of the type integer"_

![Redirects-Error](https://user-images.githubusercontent.com/7075322/56458087-389f2c80-6350-11e9-9777-1ade039c0b31.png)

**Comment by BenParizek** [comment]
@lpbouvier This is resolved in v4.0.0-beta.37
