### ISSUE TITLE
SEO Sprout breaks Live-Preview mode in Craft 3

### ISSUE THREAD

**Issue by enjinstudios** [barrelstrength/craft-sprout-seo#155]
### Description

SEO Sprout breaks the live preview mode. 

### Steps to reproduce

1. Install plugin
2. Check live preview of a single
3. Live preview shows up blank with 500 error.

### Additional info

- Craft version:  3.1.23
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.25
- Plugins & versions: 
1. - Feed Me | 4.0.0
2. - Forms | 2.5.17
3. - Freeform Pro | 2.5.17
4. - Redactor | 2.3.2
5. - Sprout SEO | 4.0.0-beta.37

**Comment by enjinstudios** [comment]
Just as a note, we installed the plugin on a fresh new instance of Craft without any plugins, and still had the same issue.

**Comment by enjinstudios** [comment]
{% if not craft.request.isLivePreview %}
  {% sproutseo 'optimize' %}
  {% endif %}

This workaround enables live preview, but obviously doesn't show SEO in the preview.

**Comment by andrelopez** [comment]
Hi @enjinstudios 

Thanks for reaching out. We're unable to recreate this issue, could you please recreate the error and send back to us a zip file of the next folder:

`storage/logs`

Please send the file to the next email address: support@barrelstrengthdesign.com

**Comment by BenParizek** [comment]
@enjinstudios We'll keep our eye out for a scenario where this occurs. Please drop us a note via support if you'd like to share your logs or db and have us look into your situation further and we'll reopen the discussion.
