### ISSUE TITLE
Leave custom sitemaps untouched

### ISSUE THREAD

**Issue by medoingthings** [barrelstrength/craft-sprout-seo#157]
### Description
I have built a custom sitemap as a template. Because the content of this sitemap needs some logic.

When I try to access this sitemap, I only get an empty document, because Sprout SEO seems to overwrite templates with the file extension .xml

### What I expect
When I create a template in my templates folder called "my-special-sitemap.xml" that this template is rendered without interference from Sprout SEO when I go to `www.mysite.com/my-special-sitemap.xml`

**Comment by BenParizek** [comment]
Hey @medoingthings.

You're right that you are running into Sprout SEO routing rules here but Sprout SEO is not hijacking all XML requests.

When you enable XML Sitemaps Sprout watches for two URL patterns. These patterns would match the following where XYZ and 123 are any combination of letters and numbers respectively:

- sitemap.xml
- sitemap-XYZ.xml
- sitemap-XYZ-123.xml

To get around this, you should be able to name your custom sitemap XML file anything that doesn't begin with `sitemap` or `sitemap-XYZ` such as: `custom-sitemap.xml`

We do have plans to add support for registering custom sitemap files in the Control Panel so they could be included in your primary sitemap index as well:
https://github.com/barrelstrength/craft-sprout-seo/issues/158

I'm going to close this out with the short term work around to name your file a pattern that falls outside the patterns that Sprout SEO is watching for and a longer term workaround being the ability to register these custom sitemaps in the CP.

**Comment by medoingthings** [comment]
That is good to know, indeed. Would be great to have that in the docs. #158 sounds good, too. Thanks!
