### ISSUE TITLE
Sort redirects by count

### ISSUE THREAD

**Issue by medoingthings** [barrelstrength/craft-sprout-seo#159]
### Description
It would be very helpful to be able to sort the list of redirects by count. The list can grow pretty long, especially with the option "Log 404 Redirects" turned on. Sorting by count would enable the user to see which urls return most 404s and add redirects accordingly.

### Additional info

- Plugins & versions: 4.0.0-beta.39

**Comment by BenParizek** [comment]
@medoingthings I agree!

Added to the list.

**Comment by BenParizek** [comment]
@medoingthings I forgot to update this thread when we released, but this is now added as of v1.1.0.
