### ISSUE TITLE
Setting unknown property: barrelstrength\\sproutlists\\elements\\db\\SubscriberListQuery::primaryModel

### ISSUE THREAD

**Issue by QswaGithub** [barrelstrength/craft-sprout-seo#166]
### Description (screenshots, logs, ...)

http://prntscr.com/oer4fe

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Below 3.1.9
- PHP version: 7.1.25
- Database driver & version:  
- Plugins & versions:

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@QswaGithub What are the steps I can take to recreate this error? It appears to be reference Sprout Lists in the error message and you've posted this issue on the Sprout SEO repo? I don't believe we use a `primaryModel` variable in either plugin. We'll need more info to help troubleshoot.

**Comment by BenParizek** [comment]
@QswaGithub As we haven't received any more info, I'm closing this out. Please feel free to reopen with more information if we can help troubleshoot further.
