### ISSUE TITLE
Redirects error with multi-site

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-seo#179]
We have a multisite, where the primary site is New Zealand, and the secondary site Australia. Creating redirects for NZ works fine, but for Australia either plan doesn't work, or throws an error.

Some scenarios:
- Select All Redirects from sidebar
- Select Australia from the multi-site dropdown
- Error: `Template not found: sprout-redirects/redirects/new/en_au`

Or
- Select All Redirects from sidebar
- Select New Zealand from the multi-site dropdown
- Error: `Template not found: sprout-redirects/redirects/new/en_nz`

Or
- Select 301 Permanent from sidebar
- Select New Zealand from the multi-site dropdown
- Works

Or
- Select 301 Permanent from sidebar
- Select Australia from the multi-site dropdown
- Either throws an error `Template not found: sprout-redirects/redirects/new/en_au`
- Or goes to the redirect template, but with `sprout-seo/redirects/new/en_nz` as the URL - creating a redirect for the wrong site.

All in all, things seem to be a bit flakey? When testing, I'm getting most of those errors when changing the multi-site dropdown in the header, even changing to the other site, then back again to the original site. Refreshing the page seems to work, but still not redirecting to the correct site.

The only way to get around these errors is to manually type the URL to edit/create a redirect for the particular site.

**Comment by BenParizek** [comment]
Thanks for reporting @engram-design. We'll test things out and follow up.

**Comment by BenParizek** [comment]
@engram-design In my initial tests I am unable to recreate this. Switching between and editing redirects between two different sites is working fine in the basic test setup I have. I've tested with hard coded Base URLs and alias web URLs. I've tested a few different Site handle naming conventions.

Can you confirm what version of Craft and Sprout SEO you are using? Any more details you can provide about how things may be configured that might help me recreate?

**Comment by engram-design** [comment]
@BenParizek Odd, I can't seem to replicate this either, I'll double check everything...

**Comment by BenParizek** [comment]
Ok, closing out for now. Please reopen if you run into something again.
