### ISSUE TITLE
getSocialProfiles not returning correct data in multisite setup

### ISSUE THREAD

**Issue by Coalescent** [barrelstrength/craft-sprout-seo#184]
### Description (screenshots, logs, ...)

When using `{% set socialProfiles = craft.sproutSeo.getSocialProfiles() %}` on a non-primary website, it returns data for the primary website. It's not clear if/how one gets to this data for the secondary site in question. I tried passing the site id `{% set socialProfiles = craft.sproutSeo.getSocialProfiles(2) %}` but that makes no difference.

I assume that method _should_ be returning data for the site it's being called for. FYI, something like `{% sproutseo 'optimize' %}` works as expected and returns the correct data for the site/entry in question.

### Steps to reproduce

1. Create a second site and add some social profiles in the cp
2. Use the method above to get them in a template for that site

### Additional info

- Craft version: Craft Pro 3.4.2
- PHP version: 7.3.8
- Database driver & version:  MySQL 5.7.26
- Sprout SEO 4.2.11

**UPDATE**: Same behaviour for this: `{% set globals = craft.sproutSeo.getGlobalMetadata() %}`

**Comment by BenParizek** [comment]
Thanks @Coalescent 

I'll take a closer look and make sure we support multi-site for those tags.

**Comment by Coalescent** [comment]
Is there any eta on a possible fix for this and the other current bugs? Thanks.

**Comment by BenParizek** [comment]
@Coalescent I'm testing the release now but running into a few details that may take me a bit longer to sort out. I'm trying to get it out as soon as I can, just juggling a few commitments.

**Comment by BenParizek** [comment]
@Coalescent This should be resolved in Sprout SEO v4.4.1. These methods now support passing in the `currentSite` variable which is available as a global variable in Craft templates.

I've also updated the examples in the docs:
https://sprout.barrelstrengthdesign.com/docs/seo/global-metadata.html
