### ISSUE TITLE
TypeError in barrelstrength\sproutseo\services\ElementMetadata.php

### ISSUE THREAD

**Issue by TRowbotham** [barrelstrength/craft-sprout-seo#186]
### Description (screenshots, logs, ...)

Commit 80c5d5c appears to be the culprit as the return value of `barrelstrength\sproutseo\services
ElementMetadata::getElementMetadataFieldHandle()` is no longer checked for null and `craft\base\Element::getFieldValue()` only accepts a string.

Argument 1 passed to craft\base\Element::getFieldValue() must be of the type string, null given, called in /mnt/c/Users/Manny/Downloads/www/restoremyfloors_dev/vendor/barrelstrength/sprout-seo/src/services/ElementMetadata.php on line 40

### Steps to reproduce

1. Update to Sprout SEO 4.3.0
2. Load website

### Additional info

- Craft version: 3.4.4.1
- PHP version: 7.2.24
- Database driver & version:  MySQL 5.7.25
- Plugins & versions: 

Plugin | Version
-- | --
CKEditor | 1.0.0-beta.2
Contact Form | 2.2.6
Contact Form Honeypot | 1.0.2
Contact Form Validation | 0.0.1
Phone Number | 1.3.0
Sprout SEO | 4.3.0
Store Hours | 2.1.1.1

[Stack trace.txt](https://github.com/barrelstrength/craft-sprout-seo/files/4172690/Stack.trace.txt)

**Comment by BenParizek** [comment]
Thanks @TRowbotham 

I've just released v4.3.2 which reverts that change and should get things working again.
