### ISSUE TITLE
Attempt to edit an Entry results in 500 error -Call to undefined function barrelstrength\sproutseo\services\is_iterable()

### ISSUE THREAD

**Issue by markmiddleton** [barrelstrength/craft-sprout-seo#189]
### Description

barrelstrength/sprout-seo/src/services/ElementMetadata.php on line 188 contains "is_iterable()" function.  is_iterable is supported after PHP 7.1, but Craft supports 7.0

### Steps to reproduce

1. install craft using PHP 7.0
2. upgrade Sprout SEO (pro) plugin 
3. in control panel, edit an entry

### Additional info

- Craft version:  3.4.6.1
- PHP version: 7.0
- Plugins & versions: Sprout SEO (pro) version 4.3.3

**Comment by BenParizek** [comment]
See: https://github.com/barrelstrength/craft-sprout-seo/pull/190

**Comment by BenParizek** [comment]
@markmiddleton This has been corrected in v4.4.1
