### ISSUE TITLE
Not possible to delete Verify ownership item

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-seo#195]
### Description (screenshots, logs, ...)

Deleting of Sprout SEO / Globals / Verify ownership items is not possible - erasing the item from list and saving the page leads to server error.

### Steps to reproduce

1. create multisite setup
2. add Pinterest with its code to SEO Globals Verify Owner ship
3. save
4. try to delete

### Additional info

- Craft version: latest
- PHP version: 7.X
- Database driver & version:  
- Plugins & versions: Sprout SEO  latest

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@lexislav This has been resolved in v4.4.2
