### ISSUE TITLE
Meta fields get mapped when creating new content but not when editing existing content from the same entry type

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#196]
A user reports:

_I've noticed that the meta fields get mapped when creating new content but not when editing existing content from the same entry type. Existing content still uses global seo meta's._

**Comment by vsteenhoudt** [comment]
Hey @BenParizek,
Sorry, was my mistake. I had defined to entry type to one section but one of the entry types didn't have the sprout metafield defined. So I was looking at the wrong content type for the existing entries.
Sorry about that. Seems to work perfect!
Cheers!
Valentijn

**Comment by BenParizek** [comment]
Thanks for confirming @vsteenhoudt. Onward!
