### ISSUE TITLE
Can't save Website Identity for Electrician

### ISSUE THREAD

**Issue by rogerdawkins** [barrelstrength/craft-sprout-seo#198]
### Description (screenshots, logs, ...)

I can save all values in the Globals section with the exception of one. In the Website Identity option I need to set Electrician, which is done as Organization > Local Business > Home And Construction Business > Electrician. I can select all those but when I then Save the settings are NOT stored.

I have tried other sequences and they work OK. From my simple testing it works ok if there are only three levels set, i.e. Organization > Local Business > Child Care works fine and is stored but when you choose a third level that has options for a fourth level it fails to save.

### Steps to reproduce

1. Just try any Website Identity with four levels and try to save it.
2.

### Additional info

- Craft version: 3.4.11
- PHP version: 7.2.16
- Database driver & version:  MySQL 5.7.19
- Plugins & versions: Redactor 2.6.1

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks @rogerdawkins. We'll let you know when we have a fix.

**Comment by BenParizek** [comment]
@rogerdawkins This is addressed in the latest release of Sprout SEO v4.6.1.

The issue turned out to just be a display bug in the CP. The data was saved correctly but the dropdowns were not loading the data properly.
