### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by 3dgroup** [barrelstrength/craft-sprout-seo#203]
Hi, Getting the following error when updating:

yii\base\ErrorException: Undefined index: enableMetadataRendering

Migration: barrelstrength\sproutseo\migrations\m200420_000000_update_settings_model

**Comment by BenParizek** [comment]
Thanks @3dgroup. I'll have a fix out shortly.

**Comment by BenParizek** [comment]
@3dgroup I've just released v4.6.0 which should resolve this issue.
