### ISSUE TITLE
[3.5.] Settings getAcceptsJson() on string

### ISSUE THREAD

**Issue by Jan10** [barrelstrength/craft-sprout-seo#221]
### Description (screenshots, logs, ...)

In Craft CMS 3.5.0 Sprout Seo -> Settings

Error: Call to a member function getAcceptsJson() on string in /home/ubuntu/sites/polsterando/vendor/craftcms/cms/src/web/Controller.php:183
Stack trace:
0 /home/ubuntu/sites/polsterando/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
1 /home/ubuntu/sites/polsterando/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction()
2 /home/ubuntu/sites/polsterando/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
3 /home/ubuntu/sites/polsterando/vendor/craftcms/cms/src/web/Application.php(280): yii\web\Application->handleRequest()
4 /home/ubuntu/sites/polsterando/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
5 /home/ubuntu/sites/polsterando/web/index.php(22): yii\base\Application->run()
6 {main}

### Steps to reproduce

1. Install Craft CMS 3.5.0
2. Install the Sprout Seo Plugin
3. Click on Sprout Seo -> "Settings"

### Additional info

- Craft version: Craft CMS 3.5.0
- PHP version: 7.4.7
- Plugins & versions: 4.6.3

**Comment by BenParizek** [comment]
@Jan10 We'll be releasing a new major version of Sprout SEO with Craft 3.5 support within a few weeks of the Craft 3.5 release. I'll update this thread once we do.

**Comment by codyjames** [comment]
@BenParizek Any updates here?

**Comment by BenParizek** [comment]
@codyjames Still working on 3.5 support. I'll avoid estimating a timeline this time but it's a priority. 

My comment here explains a bit more what I'm working through:
https://github.com/barrelstrength/craft-sprout-forms/issues/521#issuecomment-685744505

**Comment by schellenbergk** [comment]
@BenParizek , any ETA on this update?

**Comment by faithmcqueen** [comment]
@BenParizek wondering if there are any updates to this?

**Comment by BenParizek** [comment]
This has been resolved in Sprout SEO v4.6.4 which adds Craft 3.5 support.
