### ISSUE TITLE
yii\base\ErrorException: Cannot use barrelstrength\sproutseo\fields\ElementMetadata as ElementMetadata because the name is already in use

### ISSUE THREAD

**Issue by TRowbotham** [barrelstrength/craft-sprout-seo#222]
### Description (screenshots, logs, ...)

```bash
yii\base\ErrorException: Cannot use barrelstrength\sproutseo\fields\ElementMetadata as ElementMetadata because the name is already in use in /usr/local/apache2/htdocs/vendor/barrelstrength/sprout-seo/src/services/Settings.php:10
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

`ElementMetadata` is already defined in this namespace from https://github.com/barrelstrength/craft-sprout-seo/blob/develop/src/services/ElementMetadata.php#L26. `barrelstrength\sproutseo\fields\ElementMetadata` will need to be aliased to something else to avoid conflicts.

### Steps to reproduce
1) Install Sprout SEO

### Additional info

- Craft version: 3.4.5
- PHP version: 7.0.2
- Database driver & version:  5.6.48
- Plugins & versions: Sprout SEO 4.6.3

**Comment by BenParizek** [comment]
This should be resolved in Sprout SEO v4.6.4 which adds Craft 3.5 support.
