### ISSUE TITLE
yii\base\ErrorException: Cannot use CommerceGuys\Addressing\Address as Address

### ISSUE THREAD

**Issue by TRowbotham** [barrelstrength/craft-sprout-seo#223]
### Description (screenshots, logs, ...)

```bash
yii\base\ErrorException: Cannot use CommerceGuys\Addressing\Address as Address because the name is already in use in /usr/local/apache2/htdocs/vendor/barrelstrength/sprout-base-fields/src/services/AddressFormatter.php:11
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
barrelstrength/craft-sprout-base-fields#1 {main}
```

`Address` is already defined in this namespace from https://github.com/barrelstrength/craft-sprout-base-fields/blob/v1/src/services/Address.php#L36, so `CommerceGuys\Addressing\Address` will need to be aliased to something else.

### Steps to reproduce
1) Install Sprout SEO - installation fails with above stack trace.

### Additional info

- Craft version: 3.4.5
- PHP version: 7.0.2
- Database driver & version:  Mysql 5.6.48
- Plugins & versions: Sprout SEO 4.6.3

Manually fixing this error leads to the error in  barrelstrength/craft-sprout-seo#222

**Comment by BenParizek** [comment]
This should be resolved in Sprout SEO v4.6.4 which adds Craft 3.5 support.
