### ISSUE TITLE
Plugin settings page not accessible on Craft 3.5

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-seo#225]
Plugin settings page not accessible on craft 3.5.

### Additional info

- Craft version: Craft Pro 3.5.9
- Plugins & versions: 4.6.3

**Comment by lexislav** [comment]
Due to this issie I am not able to turn on Sitemap for one of sites. Is there any workaround for that? Thanks

**Comment by BenParizek** [comment]
This has been resolved in Sprout SEO v4.6.4 which adds Craft 3.5 support.
