### ISSUE TITLE
User is not permitted - redirects

### ISSUE THREAD

**Issue by DrewBold** [barrelstrength/craft-sprout-seo#226]
![Screenshot_20200929_101802_com android chrome](https://user-images.githubusercontent.com/66840687/94570668-14ca6080-023d-11eb-943a-1ae1e44729ba.jpg)
Error user is not permitted when saving redirects. User has all sprout SEO permissions assigned in CMS.

Craft Pro 3.4.23
Sprout SEO pro 4.6.3

**Comment by DrewBold** [comment]
Any progress on this?

**Comment by BenParizek** [comment]
@DrewBold Thanks for reporting. I just released Sprout SEO v4.6.5 which should resolve this.

**Comment by DrewBold** [comment]
Brilliant - Fixed, thank you!
