### ISSUE TITLE
sproutseo 'optimize' no longer outputting meta tags after update to 4.6.3

### ISSUE THREAD

**Issue by isjackwild** [barrelstrength/craft-sprout-seo#227]
### Description (screenshots, logs, ...)
I have been using Sprout SEO (paid version) successfully on a website for a client, however we've noticed that after recently updating to 4.6.3, the `{% sproutseo 'optimize' %}` tag in the twig template no longer outputs anything. Prior to upgrading it was working fine. This is the same across the development, staging and production environments.

### Additional info

- Craft version: 3.5.7
- PHP version: 7.3.10
- Database driver & version:  MySQL 8.0.17
- Plugins & versions: Craft Commerce 3.1.12

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by isjackwild** [comment]
I realised that the issue was caused because the config setting `enableRenderMetadata' => true | false` had defaulted to false for some reason, and because of issue #225 I could not access the settings to turn it on. I managed to get around the issue by using `config/sprout-seo.php` to set the config instead, however issue #255 is still present.

**Comment by BenParizek** [comment]
This migration issue should be fixed for folks upgrading to v4.6.8.

The manual fix for anybody that updated prior to that release who doesn't want to re-migrate would be to do as is described above, and manually re-enable the "Automatically render metadata" setting in `Sprout SEO -> Settings -> Metadata`
