### ISSUE TITLE
Migration: Unknown column 'pluginId'

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#228]
See task

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_342x9)

**Comment by SwiseWeb** [comment]
I assume this is related to the recent change to the Craft `migrations` table. We're in the process of migrating a site from Craft 2 to 3 and just hit this bug during the migration.

I ended up looking through all the Sprout migrations for instances of `pluginId` and found that there is only 1 in the `m180619_000011_address_table.php` file. I then updated line 36 from `->where(['pluginId' => $plugin['id'], 'type' => 'plugin', 'name' => 'm180625_000001_address_table'])` to `->where(['track' => 'plugin:sprout-seo', 'name' => 'm180625_000001_address_table'])` to match the new column structure for the migrations table and reran the migrations. Everything ran just fine after that change and I'm not noticing any issues in the DB now.

I assume you'd probably need some logic based on the Craft version here, but are you able to confirm that the above change is a workable solution in the interim?

**Comment by BenParizek** [comment]
@SwiseWeb Looks like you may be on to what is happening here regarding the change in how Craft stores that plugin value in the db. I think your solution should probably work and let you keep moving forward.

I'm currently working through the outstanding migration issues we have and will update here if I notice anything that would change my comment down the road.

**Comment by BenParizek** [comment]
This migration issue should be addressed in the latest release of Sprout SEO. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, I'd recommend holding off on updating until we get Sprout SEO v5.0 out the door which should get things into a lot better shape and address a number of smaller issues all at once.
