### ISSUE TITLE
sitemap.xml gives this error: getTotalElementsPerSitemap() must be of the type int, string returned

### ISSUE THREAD

**Issue by alexagui** [barrelstrength/craft-sprout-seo#229]
### Description (screenshots, logs, ...)     
TypeError: Return value of barrelstrength\sproutbasesitemaps\services\XmlSitemap::getTotalElementsPerSitemap() must be of the type int, string returned in /vendor/barrelstrength/sprout-base-sitemaps/src/services/XmlSitemap.php:371
Stack trace:

### Steps to reproduce

1. We get this error when we visit /sitemap.xml

### Additional info   

- Craft version: Pro 3.5.13.2
- PHP version: 7.3.23
- Database driver & version:  MariaDB 10.3.25
- Plugins & versions: Sprout SEO 4.6.3

NOTE we just migrated this site from Craft 2 to Craft 3

**Comment by BenParizek** [comment]
@alexagui I believe this issue has to do with the `totalElementsPerSitemap` setting. But I'm not sure how. In my tests it is working both with an integer and a string.

Can you review and resave the Total Elements Per Sitemap setting on in the Sitemaps settings area: `/admin/sprout-seo/settings/sitemaps` and see if that helps?

Let me know what you find.

**Comment by alexagui** [comment]
Hi @BenParizek 

That was it. Once I explicitly set **Total Elements Per Sitemap** it worked.

Thanks!

**Comment by BenParizek** [comment]
Glad to here it, Alex. I'm going to keep this open until I have a chance to review it and fix how the issue originated in a migration.

**Comment by BenParizek** [comment]
This migration issue should be fixed in v4.6.8.

**Comment by bymayo** [comment]
As part of this, we needed to set this value to fix the issue,  but the change wasn't added to project config yaml files and we can't make admin changes on production. 

Does this plugin not use project yaml?

**Comment by BenParizek** [comment]
@bymayo The current setting for this is in the `sprout_settings` table in the db. In our next release, we'll be standardizing our settings to use the project config yaml.
