### ISSUE TITLE
SEO Lite - Template Overrides using 'do craft.sproutSeo.meta' not working

### ISSUE THREAD

**Issue by afairhurst** [barrelstrength/craft-sprout-seo#231]
### Description

Can I set metadata in templates using SEO Lite, or is this a SEO Pro feature? The docs don't indicate Pro is required; Am I missing a setting somewhere to enable Template Overides?

REF: [Template Overides](https://sprout.barrelstrengthdesign.com/docs/seo/template-overrides.html#templating)

{% do craft.sproutSeo.meta({
    title: 'My Title Override',
}) %}

{% sproutseo 'optimize' %}

### Steps to reproduce

1. do craft.sproutSeo.meta code added to entry template
2. sproutseo 'optimize' code added to _layout
3. Rendered page does not use the title override.

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38  
- Plugins & versions: 4.6.4

**Comment by BenParizek** [comment]
@afairhurst Template Overrides are only available in the Pro edition. It is noted on the [Craft plugin features page](https://plugins.craftcms.com/sprout-seo) but I'll consider adding a note to the docs.
