### ISSUE TITLE
Updating Redirects can delete them

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#233]
https://github.com/barrelstrength/craft-sprout-base-redirects/pull/9

**Comment by encaps** [comment]
hi there @BenParizek  - I am experiencing this issue...is there a fix planned for this or can I do anything to prevent this from happening?

**Comment by BenParizek** [comment]
This is fixed in the latest version of Sprout SEO and Sprout Redirects.
