### ISSUE TITLE
Plugin breaks UI in craft 3.6.2

### ISSUE THREAD

**Issue by lassemt** [barrelstrength/craft-sprout-seo#236]
### Description (screenshots, logs, ...)
After updating to craft 3.6 the entry editor UI become unresponsive when Sprout SEO plugin is active. This is the error message I get when the plugin is active.
![Screenshot 2021-02-01 at 23 28 19](https://user-images.githubusercontent.com/2833312/106526212-7fd6bd00-64e5-11eb-9fa8-15ab6919004f.png)

Buttons such as publish draft, lightswitch, etc. becomes unreactive. I've tried deleteing CP caches without luck. 

### Steps to reproduce

1. Updatae to Craft 3.6.2
2. Try toggleing lightswitch field in entry with SEO field.

### Additional info
PHP version	7.4.9
OS version	Darwin 19.6.0
Database driver & version	MySQL 5.7.30
Image driver & version	GD 7.4.9
Craft edition & version	Craft Pro 3.6.2
Yii version	2.0.40
Twig version	v2.14.3
Guzzle version	7.2.0

Sprout SEO | 4.6.5

**Comment by BenParizek** [comment]
@lassemt Are you still running into this issue on the latest version of Craft? I haven't yet been able to recreate this and can get an Entry to Publish a Draft and update a Lightswitch field with the Sprout Metadata field enabled. 

Can you perhaps screenshot your Metadata field settings so I can make sure I'm testing the same scenario?
