### ISSUE TITLE
Entry's element metadata is not preserved when publishing a draft

### ISSUE THREAD

**Issue by akselikap** [barrelstrength/craft-sprout-seo#241]
### Description (screenshots, logs, ...)

When publishing an entry draft the element metadata contained in the draft is deleted.

### Steps to reproduce

1. Create an entry type with the element metadata
2. Create new entry with the type of the entry created in step 1.
3. Set a value to meta title
4. Publish the entry
5. View the entry and see that meta title is empty
6. Set the meta title again and save.
7. View the entry and see that meta title is as it's supposed to be
8. Make a draft and publish it.
9. View the entry and see that meta title is gone again.

### Additional info

- Craft version: Craft Pro 3.6.12
- PHP version: 7.4.13
- Database driver & version:  MySQL 5.7.30
- Plugins & versions: Sprout SEO 4.6.8

Also viewing previous revisions of the entry don't show the element metadata values at all. This used to work on Craft Pro 3.6.11.1 and Sprout SEO 4.6.7. Could this be due to changes in Craft Pro 3.6.11.2?

**Comment by BenParizek** [comment]
Thanks for reporting. Craft has added several changes to the Drafts/Revisions workflow in various 3.x releases but this could also just be something we overlooked. I'll look into it and update this thread once I have a fix out.

**Comment by enjinstudios** [comment]
it's not preserving at all in 3.7 and just disappears from all fields.

**Comment by BenParizek** [comment]
This should be addressed in v4.6.9
