### ISSUE TITLE
Craft 4 Support?

### ISSUE THREAD

**Issue by wunderbaresnet** [barrelstrength/craft-sprout-seo#261]
### The problem (description, use case, screenshots...)
The missing support for Craft 4 means I can't update to C4...

### The solution (that feature you'd like to see)
Please make the plugin work for C4.

### Alternatives you've considered
Thanks.

**Comment by BenParizek** [comment]
I'm in the process of getting all of our plugins updated to Craft 4. I can't set a release date yet, so if timing is an issue you may want to consider alternatives. The upgrade is taking longer as we re-architect some underlying structural issues that were causing ongoing problems and work toward making the plugins more reliable and easy to maintain moving forward.

**Comment by BenParizek** [comment]
I've posted an official Craft 4 thread that we will update once we get a release out:
https://github.com/barrelstrength/craft-sprout-seo/issues/262
