### ISSUE TITLE
Find an alternative for crodas/text-rank because it's not going to pass minimum stability

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#55]

**Comment by joeswann** [comment]
This just prevented me from installing on Craft 3 I think just FYI. Tried minimum stability setting dev to no avail.

```
Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for barrelstrength/sprout-seo v3.5.0 -> satisfiable by barrelstrength/sprout-seo[v3.5.0].
- barrelstrength/sprout-seo v3.5.0 requires crodas/text-rank dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see for more details.
- It's a private package and you forgot to add a custom repository to find it

Read for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.```

**Comment by BenParizek** [comment]
@joeswann Sprout SEO v3.x is for Craft 2. You'll want to install v4.x for Craft 3. We removed the dependency to `crodas/text-rank` in v4.0.0-beta.4

Can you make sure you have the latest version of Sprout SEO v4.x referenced in your composer file or try installing via the plugin store?

**Comment by jsunsawyer** [comment]
This is also blocking me from installing. Trying to install via the plugin store, but it shows as version 3.5.

![screen shot 2018-08-30 at 4 38 32 pm](https://user-images.githubusercontent.com/1007191/44884968-337f5700-ac73-11e8-9eb7-4bed120e5986.png)

**Comment by BenParizek** [comment]
@joeswann @jsunsawyer Reopening this. We're looking into this further.

**Comment by BenParizek** [comment]
@joeswann @jsunsawyer The issue causing this error has been fixed in the Craft Plugin Store. If you'd like to try to download Sprout SEO again, the latest is now available in the store and this should no longer be an issue.
