### ISSUE TITLE
Sitemaps page throws an error with a single site and no siteSettings or groupSettings stored in the db for the Sprout SEO settings

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#97]
### Steps to reproduce

1. Install a fresh version of Sprout SEO
2. Make sure to not save any settings from the Sprout SEO -> Settings tab 
3. Visit the Sitemaps page to see error: http://share.barrelstrength.co/413L1O1v1h0g

For a single site, we should ensure that we default to the primary Site if none of those settings exist.

### Notify

- Selvin on Slack

**Comment by andrelopez** [comment]
This only happens on Craft2 to craft3 migration
