### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by klick** [barrelstrength/craft-sprout-seo#98]
### Description

Occurs on front end (any page) as well as in the cp (Plugin Settings “Sections” and “Sitemap”).
(I’m new to Sprout SEO so don’t really know, where to start.)

Edit: Occurs only on localhost.

### Additional info

- Craft version: 2.7.0
- PHP version: 7.2
- Database driver & version: MYSQL & 5
- Plugins & versions: 3.4.2

**Comment by BenParizek** [comment]
@klick Craft 2 just recently added PHP 7.2 support. We're in the process of getting releases out to do the same. You can revert to PHP 7.1 to get things working for now and we'll let you know when we have an update out.

**Comment by klick** [comment]
Hi Ben, thanks. That is good news.

**Comment by BenParizek** [comment]
@klick This issue is resolved in v3.5.1
https://github.com/barrelstrength/craft-sprout-seo/releases/tag/v3.5.1
